name = "StaTech Industry"
author = "static"
version = "1.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b676b05abdebbad79970dc1231c389acdd69f8c16dabb21fdef4752b44eda128"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
