name = "StaTech Industry"
author = "static"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0a5ca69c464f9a3f8ae5ec208e39fb4a025efb03ae7a2f8948286830a95f885"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
