name = "StaTech Industry"
author = "static"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f99e77d1f033775d5527b721733f6aea285fe21452502322a3fc30f13d7889ae"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
