name = "StaTech Industry"
author = "static"
version = "1.0.5hotfix"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e13c5b8f56f8ba46cd0b86e1c42bc839928ecd0d172e68c9d507940e12112410"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
