name = "StaTech Industry"
author = "static"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bacd4d0659e483418000771aef9fc742f6bffa2c88ed4de01d93e00ea2c505a"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
