name = "StaTech Industry"
author = "static"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "737257a92784edda51907570e80bf6d0013b96545a76df4f881330b09885b7e9"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
