name = "StaTech Industry"
author = "static"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "635a2f6e9ffdb039729cdda7cd54654be7ce77e835fc988824c7b861d960dd79"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
