name = "StaTech Industry"
author = "static"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f06d7c9ec2fa48ca46b32209cbe7614f94df51516369af5f50f7e783b6bc3ec"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
