name = "StaTech Industry"
author = "static"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6451f324711ecab83d11a90ea35565c3204ac5a92b3ce7ddb7bf847239c98f00"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
