name = "StaTech Industry"
author = "static"
version = "1.1.4hotfix"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7de2764aaeaaeec3964fb41360c149368300c5ec78d576582b3228d7e0e85e60"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
