name = "StaTech Industry"
author = "static"
version = "1.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5231cd2d9186e676dd4a0baa613c4d2f29a0cc621a429e935db07bbdc7271230"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
