name = "StaTech Industry"
author = "static"
version = "1.1.5hotfix"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aff1a6a9a1fbbeae119c33a6e341d7038ffb8d3cf8b59d1cd7441990896fb9b1"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
