name = "StaTech Industry"
author = "static"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c66a7149d3cc447e3dfc04f6a4e018f6bd7f95a7aa96ad6d581d8b4d2efd2e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
