name = "StaTech Industry"
author = "static"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25d20d1f48622a187d121c53364357d1cf6177fc8eb15ef177bbb6bcf0518a49"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
