name = "StaTech Industry"
author = "static"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d49fa314969c3755c9999045e1076bd66048f8358fe5379aeddf53904d93b56c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
