name = "StaTech Industry"
author = "static"
version = "1.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7f12f50c2d6d989d87a3fc87b03b00ad342a81f8d46d045f9278dbcc6246df"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
