name = "StaTech Industry"
author = "static"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39f33132e9cdaf3720c6f23cd9850070590a31fae2612e47fc8caac9944a3994"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
