name = "StaTech Industry"
author = "static"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a21966d82d56ff269e1ec2d1a20adfec294b839eebef63abf7ede523ce858467"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
