name = "StaTech Industry"
author = "static"
version = "1.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dc099ac9b06d2a70d6cb880fb01efe08e4b9622dc283ebda510ce30ac150bb1"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
