name = "StaTech Industry"
author = "static"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b21025db8091523ff6836dad5b1b3fd2dd3f15dac3b9d6077c833599246522c3"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
