name = "StaTech Industry"
author = "static"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b78db9f52b67e76459e4dbc1741ca601bb4025bc4b3d33b7405b2b1db02b03f"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
