name = "StaTech Industry"
author = "static"
version = "1.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b17236b0edab2b3c61ae527163a83b6129217d11c657b6c8a51caa48a1b35d3"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
