# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				cow = true
				chicken = true
				sheep = true
				glow_squid = true
				spider = true
				creeper = true
				bat = true
				item = true
				skeleton = true
				witch = true
				zombie = true
				cave_spider = true
				squid = true
				pig = true

			[light_sources.settings.entities.naturalist]
				butterfly = true
				bluejay = true
				canary = true

			[light_sources.settings.entities.betteranimalsplus]
				pheasant = true
				butterfly = true
				squirrel = true
				boar = true
				turkey = true

			[light_sources.settings.entities.promenade]
				duck = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

